---
- name: secure SSH
  hosts: all
  become: true

  handlers:
    - name: restart ssh
      service: name={{ ssh_service }} state=restarted

  tasks:
    # alternately, consider http://docs.ansible.com/ansible/playbooks_best_practices.html#operating-system-and-distribution-variance
    - name: include os-specific variables
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
        - "vars/defaults.yml"

    - name: update SSH configuration
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line:   "{{ item.line }}"
        state: present
      with_items:
        - regexp: "^PasswordAuthentication"
          line:   "PasswordAuthentication no"
        - regexp: "^PermitRootLogin"
          line:   "PermitRootLogin no"
        - regexp: "^Port"
          line:   "Port {{ ssh_port }}"
      notify: restart ssh
